project2/config/routes.rb
Rails.application.routes.draw do
  
  root to: 'sessions#new'
  delete '/sessions' => 'sessions#destroy', as: 'logout'
  resource :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create]
  resources :invitations, only: [:index, :edit, :update, :destroy, :new, :create]

end

project2/app/models/invitation.rb
class Invitation < ActiveRecord::Base

	belongs_to :inviter, :class_name => "User", foreign_key: :inviter_id, inverse_of: :inviter_invitations

	belongs_to :invitee, :class_name => "User", foreign_key: :invitee_id, inverse_of: :invitee_invitations
end

project2/app/models/user.rb
 require 'bcrypt'
class User < ActiveRecord::Base
	has_secure_password

	has_many :inviter_invitations, :class_name => "Invitation", foreign_key: :inviter_id, inverse_of: :inviter

	has_many :invitee_invitations, :class_name => "Invitation", foreign_key: :invitee_id, inverse_of: :invitee

end

project2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

project2/app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def index
    @invitations = Invitation.all
  end

  def edit
  end

  def update
  end

  def destroy
    #
    @invitation = Invitation.where(id: params[:id]).first
    #admin should be the only ones delete ***Future 
    @invitation.destroy
    redirect_to invitations_path
  end

  def new
    @invitation = Invitation.new
  end

  def create
    invitation = Invitation.new(params.require(:invitation).permit(:title, :description))
    if invitation.save
      # Interest of time
      redirect_to invitations_path
    end
  end
end

project2/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	# the session that we have is based on a user logging in, so login form is taking queues from user 
  	@user = User.new
    if params[:user_created] == 'true'
      @user_created_message = 'User successfully created!'
    end
  end

  def create
  	# This is here to raise the red page of death on purpose   	# raise params.inspect

  	# Find the user by their email
  	# If you use find, you may get a red screen, so it's better to use where
  	# the first will bring back nothing if no instance of User. Otherwise,  
  	u = User.where(email: params[:user][:email]).first
  	# If user is not equal to nil and you authenticate the password (true or false?)
  	if u != nil && u.authenticate(params[:user][:password])
  		# set the session to the browser. saving the session id here, not saving it in the database but here as a cookie
  		# Session - intrinsic to rails and is a baked in rails property, different from the sessions we made
  		session["user_id"] = u.id.to_s
  		redirect_to invitations_path
  end
end

  def destroy
  	session.destroy
    redirect_to new_session_path
  end
end

project2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  def create
  	user = User.new(params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation))
    	if user.save
    		# Interest of time
    		redirect_to new_sessions_path
    	end
    end
    # POST /users
  # POST /users.json
 
    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.welcome_email(@user).deliver_later
 
        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
end
  def show
  end

  def edit
  end





 

project2/app/helpers/application_helper.rb
module ApplicationHelper
end

project2/app/helpers/invitations_helper.rb
module InvitationsHelper
end

project2/app/helpers/sessions_helper.rb
module SessionsHelper
end

project2/app/helpers/users_helper.rb
module UsersHelper
end

project2/app/views/invitations/_form.html.erb
<%= form_for(@invitation) do |f| %>
  <% if @invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
      <% @invitation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project2/app/views/invitations/edit.html.erb
<h1>Invitations#edit</h1>
<p>Find me in app/views/invitations/edit.html.erb</p>

project2/app/views/invitations/index.html.erb
<h1>DASHBOARD</h1>

<br />

<table class="table table-striped">
  <tbody>
    <% @invitations.each do |i| %>
      <tr>
        <td><%= i.title %></td>
        <td><%= i.description %></td>
        <td><%= link_to 'Edit', edit_invitation_path(i) %></td>
        <td><%= link_to 'Delete', i, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

project2/app/views/invitations/new.html.erb
<h1>INVITE</h1>

<%= render 'form' %>

<%= link_to 'Back', invitations_path %>

project2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project2</title>

 <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Trouble shooting to find the current value of the ID so that you know which one is logged in. -->

<%= session["user_id"].inspect %>

<%= yield %>

</body>
</html>

project2/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

project2/app/views/users/index.html.erb
<h1>We Card</h1>

<body>

</body>




<!--         <iframe width="560" height="315" src="https://www.youtube.com/embed/k4YRWT_Aldo?autoplay=1" frameborder="0" allowfullscreen></iframe> -->
<!--     <div class="bottom">
        <div class="header-bottom-grid1">
            Invite
        </div>
        <div class="header-bottom-grid2">
            Record
        </div>
        <div class="header-bottom-grid3">
            Send
        </div>
    </div> -->

project2/app/views/users/new.html.erb
<h1>Sign Up</h1>
<body>

<div class="body"></div>
	<div class="grad"></div>
		<div class="header">
			<div>Sign Up</div>
		</div>
		<br>
		<div class="login">
			<%= form_for @user do |f| %>
            <%= f.text_field :first_name, placeholder: "first name" %><br /><br />
            <%= f.text_field :last_name, placeholder: "last name" %><br /><br />
            <%= f.text_field :email, placeholder: "email" %><br />
            <%= f.password_field :password, placeholder: "password" %><br />
            <%= f.password_field :password_confirmation, placeholder: "password confirmation" %><br />
            <%= f.submit "SAVE"%>
        <% end %>
    </div>

  <script src='http://codepen.io/assets/libs/fullpage/jquery.js'></script>

</body>

project2/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>